services:
  flask:
    build: .
    volumes:
      - "./instance:/app/instance"
    env_file:
      - .env
    expose:
      - "5000"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./website/presentation/static:/app/website/presentation/static:ro
    depends_on:
      - flask